### PR TITLE
Social sharing buttons and no. of words with reading time - #3

### PR DESCRIPTION
**Pull request by kennyhei**
Added social sharing buttons using Fontawesome icons and Sass.

### CODE REVIEW

**Comment by roughike** [comment]
`<offtopic>`
Is the site currently live somewhere? If not, could we set it up with [Netlify](https://www.netlify.com/) for now, so we could get automatic deploy previews for every PR?
`</offtopic>`

@ragmha @kennyhei

**Comment by kennyhei** [comment]
I don't think it is. Sounds like a good idea 👍

**Comment by roughike** [comment]
We now have deploy previews for every pull request! They can be viewed by clicking the "Show all checks" link and then "Details".

screen shot 2018-03-13 at 11 03 21 am

Also, the status of the master branch can be viewed at https://trusting-beaver-9ad7ad.netlify.com/.

**Comment by ragmha** [comment]
@kennyhei  Can you create a separate branch `feature #10 Social Buttons & reading time` and then create a pull request. It's easier to see changes that way. For more information, you can refer to [Project-Guidelines](https://github.com/wearehive/project-guidelines#git)

**Comment by kennyhei** [comment]
Np, hopefully it's okay now and I'll bookmark that link 🙂

**Pull request closed without merging**
